name: Deploy Nexus portal development environment

on:
  push:
    branches:
      - develop

env:
  AZURE_WEBAPP_NAME: portal-cliente-nexus-dev
  AZURE_RG: ArchieDev
  IMAGE_NAME: nexus-client-portal-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME_DEV }}
          password: ${{ secrets.REGISTRY_PASSWORD_DEV }}
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER_DEV }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER_DEV }}/${{ env.IMAGE_NAME }}:latest

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER_DEV }}/${{ env.IMAGE_NAME }}:latest

      - name: Azure logout
        run: |
          az logout